### ISSUE TITLE
Chat Colors Broken

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [elian1203/ezAuctions#43]
Great plugin, thank you. Have used it for years. Sadly, it has this bug on MC 1.20.1:

The in-game chat colors are broken:
https://gyazo.com/fe896687893d3188ceff948b23d5e9a0

Error:
```
[01:50:05 INFO]: PigsGoOink_ issued server command: /auc
[01:50:05 ERROR]: [ezAuctions] Missing message key in messages file! command.auction.end.help
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key command.auction.end.help
        at java.util.ResourceBundle.getObject(ResourceBundle.java:564) ~[?:?]
        at java.util.ResourceBundle.getString(ResourceBundle.java:521) ~[?:?]
        at me.elian.ezauctions.controller.MessageController.getRawMessage(MessageController.java:259) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.controller.MessageController.getComponentMessage(MessageController.java:236) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.controller.MessageController.sendMessage(MessageController.java:83) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.command.AuctionCommand.help(AuctionCommand.java:125) ~[ezAuctions.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at me.elian.ezauctions.acf.RegisteredCommand.invoke(RegisteredCommand.java:152) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.acf.BaseCommand.executeCommand(BaseCommand.java:578) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.acf.BaseCommand.execute(BaseCommand.java:513) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.acf.RootCommand.execute(RootCommand.java:99) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84) ~[ezAuctions.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-172]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2354) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2314) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:50:05 ERROR]: [ezAuctions] Missing message key in messages file! command.auction.help.help
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key command.auction.help.help
        at java.util.ResourceBundle.getObject(ResourceBundle.java:564) ~[?:?]
        at java.util.ResourceBundle.getString(ResourceBundle.java:521) ~[?:?]
        at me.elian.ezauctions.controller.MessageController.getRawMessage(MessageController.java:259) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.controller.MessageController.getComponentMessage(MessageController.java:236) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.controller.MessageController.sendMessage(MessageController.java:83) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.command.AuctionCommand.help(AuctionCommand.java:125) ~[ezAuctions.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at me.elian.ezauctions.acf.RegisteredCommand.invoke(RegisteredCommand.java:152) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.acf.BaseCommand.executeCommand(BaseCommand.java:578) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.acf.BaseCommand.execute(BaseCommand.java:513) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.acf.RootCommand.execute(RootCommand.java:99) ~[ezAuctions.jar:?]
        at me.elian.ezauctions.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84) ~[ezAuctions.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-172]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2354) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2314) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

/ver:
```
[01:51:38 INFO]: This server is running Paper version git-Paper-172 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 72e87ab)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-399 (MC: 1.17.1)
```

/plugins:
```
[01:53:03 INFO]: Server Plugins (41):
[01:53:03 INFO]: Bukkit Plugins:
[01:53:03 INFO]:  - AutomaticInventory, *BeaconEffects, BlockLocker, BossShopPro, CMI, CMILib, CommandPanels, CraftingStore, CrateReloaded, DiscordSRV
[01:53:03 INFO]:  ezAuctions, FastAsyncWorldEdit, FastChunkPregenerator, IllegalStack, InfiniteJump, Kingdoms, LibsDisguises, LuckPerms, mcMMO, MMOItems
[01:53:03 INFO]:  MobFarmManager, Multiverse-Core, MyCommand, MythicLib, MythicMobs, PlaceholderAPI, PlayerParticles, PremiumVanish, ProtocolLib, Quests
[01:53:03 INFO]:  QuickShop, ResourceWorld, SafariNet, ShopGUIPlus, SignShop, Vault, VoidChest, Votifier, VotingPlugin, WorldGuard
[01:53:03 INFO]:  *XRayDetector
```

**Comment by elian1203** [comment]
Glad to see you are happy with the plugin! It looks like you've updated the plugin from 1.0 to 2.0 and have not made the necessary changes. You will need to delete your config file and messages file and they will be regenerated.

Make sure you are using the latest version (2.0.2 at the time of writing this) and read the [2.0 release notes](https://github.com/elian1203/ezAuctions/releases/tag/2.0.0) to get more information on the changes.

**Comment by PiggiesGoSqueal** [comment]
> Glad to see you are happy with the plugin! It looks like you've updated the plugin from 1.0 to 2.0 and have not made the necessary changes. You will need to delete your config file and messages file and they will be regenerated.
> 
> Make sure you are using the latest version (2.0.2 at the time of writing this) and read the [2.0 release notes](https://github.com/elian1203/ezAuctions/releases/tag/2.0.0) to get more information on the changes.

Oh ok- I will do that, thank you!
