### ISSUE TITLE
Plugin broken

### ISSUE THREAD

**Issue by Nubebuster** [elian1203/ezAuctions#7]
Two stack traces on paper 1.16.5

java.lang.NullPointerException: null
        at net.urbanmc.ezauctions.listener.WorldChangeListener.onPlayerChangedWorld(WorldChangeListener.java:21) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor361.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-777]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:1003) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerList.moveToWorld(PlayerList.java:825) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:930) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:539) ~[patched_1.16.5.jar:git-Paper-777]
        at com.iridium.iridiumskyblock.managers.IslandManager.teleportHome(IslandManager.java:94) ~[?:?]
        at com.iridium.iridiumskyblock.managers.IslandManager.teleportHome(IslandManager.java:76) ~[?:?]
        at com.iridium.iridiumskyblock.commands.JoinCommand.execute(JoinCommand.java:75) ~[?:?]
        at com.iridium.iridiumskyblock.commands.CommandManager.onCommand(CommandManager.java:166) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-777]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-777]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-777]
        at java.lang.Thread.run(Thread.java:829) [?:?]

and 

[17:54:26] [Server thread/INFO]: NubeBuster issued server command: /auc s hand
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] Exception in command: auction start hand
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] java.lang.NullPointerException
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.urbanmc.ezauctions.command.AuctionCommand.startAuction(AuctionCommand.java:359)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.urbanmc.ezauctions.command.AuctionCommand.start(AuctionCommand.java:346)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.urbanmc.ezauctions.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.urbanmc.ezauctions.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.urbanmc.ezauctions.acf.BaseCommand.execute(BaseCommand.java:513)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.urbanmc.ezauctions.acf.RootCommand.execute(RootCommand.java:99)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.urbanmc.ezauctions.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[17:54:26] [Server thread/ERROR]: [ezAuctions] [ACF] 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by elian1203** [comment]
Something has caused your players.json to be out of sync. This could be file corruption, spigot issues or something else. Please delete plugins/ezAuctions/players.json. I will work on adding a safety check to prevent this issue from happening in the future.

**Comment by elian1203** [comment]
Safety check add in #8
